### ISSUE TITLE
COALESCE caused error

### ISSUE THREAD

**Issue by hoanghapham** [matthewoldham/dbdiagram.io-ddl-queries#1]
Hi Matt,

This is a very useful snippet! However, I encountered this error initially:
```
ERROR:  failed to find conversion function from unknown to text
```

It turned out that this line caused the problem:

https://github.com/matthewoldham/dbdiagram.io-ddl-queries/blob/00b21058432562f3bb171a5f37662fb9a4901b4c/sql/postgresql.sql#L17

If I change to `tk.column_key as column_pk,` it runs fine. My db is PostgreSQL 9.6.8.

**Comment by matthewoldham** [comment]
Thanks @hoanghapham. Great find! I had originally only tested on PG10, but it appears PG9.5/6 require an explicit typecast in the COALESCE function. I have updated the script accordingly and tested it under PG9.5, 9.6, 10, and 11.

**Comment by hoanghapham** [comment]
awesome, thanks a lot!
